# Generated by Django 5.1.5 on 2026-02-21 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The Django user who owns this account. Null for system accounts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner_name',
            field=models.CharField(blank=True, default='', help_text='Display name. Auto-set from user if linked.', max_length=200),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user'], name='wallet_acco_user_id_b853ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'USER')), fields=('user', 'asset_type'), name='unique_user_asset_account'),
        ),
    ]
